# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore SchoolDiarySystem/SchoolDiarySystem.Tests/SchoolDiarySystem.Tests.csproj
    - name: Build main project
      run: dotnet build SchoolDiarySystem/SchoolDiarySystem/SchoolDiarySystem.Domain.csproj --no-restore
    - name: SchoolDiarySystem/SchoolDiarySystem.Tests/SchoolDiarySystem.Tests.csproj --no-restore
    - name: Test
      run: dotnet test SchoolDiarySystem/SchoolDiarySystem.Tests/SchoolDiarySystem.Tests.csproj --no-build --verbosity normal
